services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - python_network

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - python_network

  app:
    build: .
    environment:
      POSTGRES_HOST: "db"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - python_network

volumes:
  db_data:

networks:
  python_network:
    driver: bridge
